// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3750o4s-MH1vJYLHftXToHx8UJ6rvsI',
    appId: '1:1083886211348:web:04e646cab53024e0163201',
    messagingSenderId: '1083886211348',
    projectId: 'crimereportingandprevent-22511',
    authDomain: 'crimereportingandprevent-22511.firebaseapp.com',
    storageBucket: 'crimereportingandprevent-22511.appspot.com',
    measurementId: 'G-WTJ5NH8BW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8SyU59kIyFEsovsMVXwzMS6b7L2xx74',
    appId: '1:1083886211348:android:7c9c44ffc7e716fa163201',
    messagingSenderId: '1083886211348',
    projectId: 'crimereportingandprevent-22511',
    storageBucket: 'crimereportingandprevent-22511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRb5hLnysk4pyR3pIzsJOgipDOPx_i8s',
    appId: '1:1083886211348:ios:e53feefac29a6b08163201',
    messagingSenderId: '1083886211348',
    projectId: 'crimereportingandprevent-22511',
    storageBucket: 'crimereportingandprevent-22511.appspot.com',
    iosBundleId: 'com.example.crimereportingAndPreventionsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVRb5hLnysk4pyR3pIzsJOgipDOPx_i8s',
    appId: '1:1083886211348:ios:adeadf0e88c0a1d0163201',
    messagingSenderId: '1083886211348',
    projectId: 'crimereportingandprevent-22511',
    storageBucket: 'crimereportingandprevent-22511.appspot.com',
    iosBundleId: 'com.example.crimereportingAndPreventionsystem.RunnerTests',
  );
}
